pharmaverse/aNCA

- R/flexible_violinboxplot.R
- inst/shiny/tabs/outputs.R
There was no unit value defined in the ORAL dataset (missing, NA) which was producing that an if() condition was neither T/F. Issue was solved addressing the condition is.na() | is.null() for cases when this label for the plot is missing or is unitless. 
**Checks**
> Solved bug in Boxplot with oral data due to missing labels for AVAL (AVALU=NA)

- inst/shiny/tabs/nca.R
Slope selection did not save correctly when edits were made
**Checks**
> Bug: Slope selection save

- inst/shiny/tabs/nca.R
Closes #31
Local NCA results download button was not working due to wrong reactive variable being used as input. Now results can be downloaded locally as .csv
Run NCA -> Click local download -> Save file and check that it matches results table
> Bug: Local NCA results download

- inst/shiny/modules/tab_data.R
- inst/shiny/tabs/nca.R
- inst/shiny/tabs/outputs.R
#90 
Closes #
#90 
User requested that for vertically long and wide tables columns should not be missing from their view when scrolling down
User should be able to see column headings, and horizontal scroll bar in same screen.
> Enhancement: fixed header for dt::datatables

- inst/shiny/modules/tab_tlg.R
- inst/shiny/tabs/nca.R
- inst/shiny/ui.R
Closes #97 
Not sure if the second button is needed at all, but I assumed that it is there for a reason. So I simply updated the second button's id to avoid collision, and updated the observer to listen to both buttons.
Another problem that I solved is the one with conditional panels. As explained in the commit message, the problem's source is the id name itself. Conditions in conditionalPanel are evaluated in javascript, and dots in id value (e.g. `rule_adj.r.squared`) are treated the JS way, producing an error when trying to index into `undefined`.
How to test features not covered by unit tests.
Please test the app functionally to make sure that all the functionalities are still working.
> 97 bug duplicated input id for submit tlg order

- inst/shiny/functions/mapping_selectize_inputs.R
- inst/shiny/modules/column_mapping.R
- inst/shiny/server.R
Closes #154 
For column mapping at the moment, grouping variables are selected manually by the user. However it would be useful if some columns are automatically selected if they are present in the data.
Main columns used for grouping:
TRTA
TRTAN
ACTARM
TRT01A
TRT01P
AGE
RACE
SEX
For pre-clinical: GROUP
The requirements for the feature to be complete:
Mapping and Filters section -> Grouping Variables
> Enhancement: Automatic selection of grouping vars

- inst/shiny/modules/column_mapping.R
- inst/shiny/modules/tab_data.R
- inst/shiny/server.R
- inst/shiny/ui.R
Closes #143 
When user has not mapped the data (define column names and accepted) it should not be able to go through other tabs (NCA or Outputs) as it can be confusing for them to see errror messages afterwards. Instead, those tabs should remain disable and perhpaps even show a notification
> Bug: Disallow user to check NCA / Outputs tabs without mapping data

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Hi everyone,
with rapid development of the package, we are just few critical features and fixes away from having a stable version of the package, which could be published on CRAN. With that, I believe it would be beneficial to introduce **instructions** and **requirements** on package versioning. Proper, semantic versioning is not an important issue at this point, but since #172 added the possibility of installing the package with `pak`, tracking changes in the development version will be beneficial.
Therefore, I would like to suggest adding the **requirement** of bumping the package version in `DESCRIPTION` file, in all PRs which introduce code changes, before merging. We could go with just incrementing the last, .9000 part of the version, as long as we wish, and then when we believe the …
> Introduce instructions on package versioning

- .github/workflows/pkgdown.yml
- DESCRIPTION
- _pkgdown.yml
Closes #74 
I have noticed our page did not have a proper workflow set up to automatically update and redeploy. The issue seemed stale, so I have picked it up and added github workflow do do exactly that.
As a follow-up, I would propose taking a look at #75 and migrating the current PDF guide to a vignette/article, so that we can build upon it in a proper fashion.
Let me know what you think!
> Documentation: Add workflow for automatic page deployment

- inst/shiny/global.R
- inst/shiny/modules/slope_rules.R
- inst/shiny/modules/slope_selector.R
- inst/shiny/tabs/nca.R
- inst/shiny/ui.R
TODO: I have messed up with the base branch, update base when #184 is merged
TODO: Wait on #177 to be merged
Addresses #121, #144 
- Updates `slope_selector` so that it no longer updates `mydata` object. Apply button has been removed. Instead, the user should click on `Run NCA` in order to update the results, which is handled by `nca.R`.
- Adds warning stating that settings has been changed and the analysis must be re-run.
- In addition, table for viewing active selections/exclusions has been modularized and only updates when results have been recalculated.
TBA
TBA
> Refactor: deload updating mydata from slope selector

- DESCRIPTION
- R/pivot_wider_pknca_results.R
- inst/shiny/modules/nca_setup.R
Closes #148 
We would like that PKNCA's automatic behaviour does not include never automatically tmax for the half life calculation and that it takes 3 points always.
Check that Tmax not included in automatic slopes
Add manual slopes- include Tmax, and only select 2 points.
This was actually an easy fix, as the PKNCA options default settings are to exclude tmax and to have min 3 points in hl calculation. And if you don't explicitly write it (so remove from PKNCAoptions), then any manual slopes will override this for those subjects.
Important to note that if you are testing the Tmax, it wont show up in the plot (because of issue #121 ), so best to check the results and see if labda.z.ix has been updated, and lambda.z.time.first.
Also, the change to pivot_wider_pknca is just temporary, to …
> Bug: Cmax in NCA Calculations

- DESCRIPTION
- R/lambda_slope_plot.R
- R/pivot_wider_pknca_results.R
- inst/shiny/modules/nca_results.R
- inst/shiny/modules/tab_nca.R
Closes #214 
During development, the derivation of start and end time has swapped occasionally between being the time from first dose, or the time from most recent dose. Due to this, there are some sections later on in the code that are inconsistent- ie some parts assume that it is time from first dose, and others that it is time from mrd. 
Lambda.z.ix is also not correct due to the start times and also the duplicates are missing.
> bug: start and end time inconsistent and duplicates missing

- DESCRIPTION
- inst/shiny/modules/tlg/tlg_module.R
Closes #228
Since we rely on `renderPrint` to display listings with original formatting, the output displays names of the elements, which looks ugly. This PR introduces changes that `unname()` the list of displayed TLGs in order to show index numbers instead of names.
Run the app, map the data, go to TLGs tab, submit default order. Check if the Listings display includes index numbers instead of names.
> Fix: do not display list names in TLG listings

- DESCRIPTION
- inst/shiny/modules/tab_tlg.R
Closes #252
Currently when the user submits an order, the tab switches automatically to Lists. The application should switch to the first populated tab - if no listings were selected, then it should switch to Graphs.
Implemented changes detect type of the first TLG from the order and switch to appropriate tab.
Run the app, map the data, go to _TLG_ tab. When submitting an order with a _Listing_ TLG, the tab should be switched to _Listings_. When the _Listing_ is removed from the order, the tab should switch to _Graphs_ upon submitting.
In this version, the plots are bugged and not rendering properly - this is fixed in #251
> Enhancement: upon submiting tlg order, switch to first populated tab

- .github/workflows/test-coverage.yml
- README.md
The workflow for test coverage failed because it could not restore system dependencies. In `admiralci` workflow the `run-system-dependencies` is set to `false` as default. In all other workflows we have it set to `true` - this change introduces the same for test coverage workflow.
> Fix: test coverage workflow failing on staged dependencies

- .github/workflows/main.yml
I have noticed that we skip the main workflow on merges with `main` - the checks are only run on the feature branch during PR, but skipped on merge commit. This should make no substantial difference - we are usually merging main into feature branch before merging into main, so the checks run before the merge are performed on identical code as after merging. However, this means checks on merge commits are skipped and lead to a red cross with `failure` label on main branch. With this change, the checks will run again after merge, giving the main branch a green checkmark and additionally confirming that everything is in order after merge.
> Chore: Run main workflow on merge with main

- tests/testthat/test-utils-slope_selector.R
Contributes to #287 
* Added tests to `tests/testthat/test-utils-slope_selector.R` for 100% coverage (covr). Added test for filter_slopes
- check tests in file `tests/testthat/test-utils-slope_selector.R`
> Enhancement: add tests utils-slope_selector (filter_slopes) - #287

- tests/testthat/test-apply_filters.R
Contributes to #287 
* Added tests to `tests/testthat/test-apply_filters.R` for 100% coverage (covr). Adds test for NULL filter in apply_filters.R
- check tests in file `tests/testthat/test-apply_filters.R`
-  ~Package version is incremented~
> test: add test where one of the filters is NULL (apply_filters) - #287

- .github/workflows/test-coverage.yml
Closes #370
The GitHub workflow for Generage badge for coverage is being cancelled on each run. The problem associated seems to be: https://github.com/actions/runner-images/issues/11101
The solution could be to substitute in the workflow ubuntu-20.04 image label with ubuntu-latest. Hopefully that will work and is an easy fix!
> chore: ubuntu-20.04 > ubuntu-latest (test-coverage.yml)

- DESCRIPTION
- inst/shiny/modules/tab_nca/slope_selector.R
Closes #212 
Buttons for selecting page for slope selector plots were not working correctly. Clicking *Previous* on the first page would crash the app, just as pressing *Next* on the last page.
Proposed solution is not ideal and the pagination system could use a rework to make the end user experience better. However, it does solve the issue at hand for now - let me know if this is good enough at the moment.
Map the data, go to NCA -> Setup -> Slope selector. Try pressing the *Previous* button on the first page. Navigate to the last page and try pressing the *Next* button.
> Fix: Page counters in `slope_selector` going past desired range

- DESCRIPTION
- inst/shiny/modules/tab_nca/descriptive_statistics.R
Closes #381 
Summary stats download will download all the parameters, not just the ones filtered by the user in the table selection. This change filters the summary data table and selects appropriate columns before downloading a file.
Run the application -> map the data -> run NCA with default parameters. Go into Results -> Descriptive statistics. Go to _Parameter to display_ and _Statistic to display_ widgets, play around with the selections - you can i.e. deselect all and select only the first one. The table should only display relevant columns with parameters and rows with relevant Statistic. This should also be true for the .csv file downloaded using button under the table.
> Bug: summary stats download not filtered

- DESCRIPTION
Sorry for this, I forgot to bump package version in #344 (a small part of the code in `flexible_violinboxplot.R` was modified)
this finishes properly the contribution to issue #287
> forgot to bump package version in #344 (add tests flexible_violinboxplot)

- tests/testthat/test-read_pk.R
Closes #383
I have noticed a typo in testing suite for `read_pk` function. The regexpr string for `expect_error` function was actually passed to the `read_pk` function instead - which caused an error and passed the check, just not the error we actually want to test for.
This PR fixes the typo and writes to temporary test file, so that `read_pk` throws `Invalid file type=` error, instead of `File does not exist` error.
> Hotfix: typo in tests for `read_pk` function

- DESCRIPTION
- inst/shiny/modules/tab_nca/nca_setup.R
Closes #397 
In NCA setup, set rule set flags to TRUE by default.
Run the application, map the default data. On the NCA -> Setup -> Settings page check if all checkboxes in **Flag Rule Sets** are selected. Run the analysis and check if flags are applied - on dummy data, there should be red-colored result rows.
> Enhancement: All flag rule sets automatically selected

- DESCRIPTION
- R/label_operators.R
- man/apply_labels.Rd
- tests/testthat/test-label_operators.R
Closes #384 
If the user uploads an RDS file, any labels already present in the data set should be carried over, and included in all further data processing.
- `apply_labels` function will preserve any existing labels in the incoming data.
- updated docstrings fixing the example usage and adding missing import statements.
- slight refactoring of the `apply_labels` function.
I think provided unit tests cover expected behavior.
You can additionally create a .rds file with custom labels by loading dummy data, applying labels manually and saving, then running the file through the app and checking if labels are preserved.
The issue references .rds files specifically (which is really the only file format that will handle label attributes for specific columns). The changes cover this case and …
> Enhancement: Preserve exisitng labels in `apply_labels`

- tests/testthat/test-utils-slope_selector.R
Contributes to #287 
Reopened from #364
* Added test for new warning (duplicated ranges)
- check tests in file `tests/testthat/test-utils-slope_selector.R`
> Enhancement: add tests utils-slope_selector (filter_slopes) - #287 v2

- DESCRIPTION
- inst/shiny/modules/tab_nca/nca_setup.R
Closes #404
Unless selected by the user AUCINT is not computed for each profile... It is rather more expected just to be computed for partial AUCs. 
Definition of Done
AUCINT is not selected by default in the tab NCA setup
Start the App > Mapping > NCA setup > Check parameters by default selected
Anything that the reviewer should know before tacking the pull request?
> bug: remove AUCINT from default parameters

- DESCRIPTION
- inst/shiny/modules/tab_visuals.R
Closes #424
Allows boxplot to show by default. This will eliminate some confusion for the users when testing the App ( specially tomorrow! ;] )
Boxplots show by default once NCA is run.
Map columns > Run NCA > Visualization > Boxplots
A default display should be there
Anything that the reviewer should know before tacking the pull request?
> fix: set PARAM as default for boxplot colors

- DESCRIPTION
- R/general_lineplot.R
Closes #171 
Individual plots when plotting by dose profile had the duplicated points (created with `dose_profile_duplicates()` labelled as the wrong dose profile because the color_var id was created before the duplicates. I moved it so that this is created afterwards and therefore matches the new duplicated points.
Individual plots -> colour by NCA_PROFILE -> plot by dose profile and select profile == 1 -> view only 1 NCA_PROFILE colour on graph and in legend.
> Bug: individual plots duplicate points when colour by profile

- DESCRIPTION
- aNCA.Rproj
- inst/shiny/modules/tab_nca/excretion_analysis.R
/data## Issue
Closes #660 
Excretion analysis table in output folder
use `dummy_adnca_sm_dataset  `in `testthat/data` folder to create excretion parameters. Export output zip.
> Enhancement: Excretion analysis in output folder
